### ISSUE TITLE
Stuck at Phone Verfication

### ISSUE THREAD

**Issue by johnnyvng** [ilyasbelfar/Outlook-Account-Creator#3]
First of all, 
Thank you for creating this awesome bot.

I've had an issue with the script when running on Windows. It's stuck at Add security info=>Phone verification and 6 captcha squares. What to do next?

**Comment by ilyasbelfar** [comment]
Hi, thank you, I really appreciate you taking the time to express that.
1- Yeah, for phone verification stuck, remember that the script uses a free proxies from sslproxies.org website, so some proxies requires OTP on Outlook account creation process...
Try again if you face this OTP step, because it is inevitable programmatically (Except for one case which is when you use your private fresh proxies list file which is a feature that I will add it in the future to let the script choose an IP:Port from your own proxies list.)
2- For FunCaptcha (6 Captcha squares) you have to make sure that Nopecha extension works well and there is no problem with it, especially this problem.
https://i.imgur.com/zA5XtwB.jpeg
Cordially.

**Comment by johnnyvng** [comment]
Appreciate it. Will try again.
